# The Nyx GitHub Action CI pipeline running on GitHub Actions

name: Nyx GitHub Action
on: [push]
# Avoid running multiple pipelines concurrently to avoid overlapping releases and tags
concurrency:
  group: project
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test the Nyx GitHub Action
      id: nyx
      # Run the action directly from the checked out repository to make sure we're testing the one that has been pushed
      uses: ./
      with:
        command: 'infer'
        # TODO: test other arguments here
        #verbosity: '--debug'
    # TODO: test the outputs from the command
    #- name: Get the output from the Nyx GitHub Action
    #  run: echo "The version was ${{ steps.nyx.outputs.version }}"

  # TODO: eventually tag and publish the action
